from pydantic import BaseModel, Field


class GeneratedQueries(BaseModel):
    """The set of search queries generated by the LLM."""
    queries: list[str] = Field(
        description="A list of 3-5 diverse and specific search queries based on the user's question. "
                    "These queries should be optimized for vector search to find relevant document chunks."
    ) 